package com.labelhub.backend.task;

import java.util.List;

public record MarketTaskResponse(
    String taskId,
    String title,
    String taskType,
    String taskTypeKey,
    String description,
    List<String> tags,
    String schemaVersionId,
    int remainingQuota,
    int totalQuota,
    String deadline,
    Double rewardPerItem,
    String rewardCap,
    String assignStrategy,
    List<String> mediaTypes,
    String ownerName,
    boolean aiReviewEnabled,
    boolean llmAssistEnabled,
    String aiReviewRule,
    String publishedAt,
    Integer maxClaimPerUser,
    boolean claimedByMe,
    String state,
    boolean expired,
    boolean claimable,
    String statusLabel,
    boolean rewardCapExceeded,
    String rewardCapMessage,
    Double monthlyAcceptedReward,
    Double monthlyPendingReward,
    Double monthlyProjectedReward,
    Double monthlyRewardCap) {}
